version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - "1234:1234" # NPM Parcel port.
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules

volumes:
  node_modules_data: